###
GET http://localhost:3000

###
GET http://localhost:3000/movies

###
GET http://localhost:3000/movies?genre=action

###
GET http://localhost:3000/movies/6744ab79281b9a23f9a6295e

###
POST http://localhost:3000/movies
Content-type: application/json

{
    "title": "3_The Shawshank Redemption",
    "year": 1994,
    "director": "Frank Darabont",
    "duration": 142,
    "poster": "https://mgallegoa.github.io/vanillaJS/basic_express_movies_mvc/public/images/The_Shawshank_Redemption.webp",
    "genre": ["Drama"],
    "rate": 9.3,
    "password": "Manuel",
    "confirm": "Manuel"
}

###
PATCH http://localhost:3000/movies/dcdd0fad-a94c-4810-8acc-5f108d3b18c3
Content-type: application/json

{
  "title": "Updated title and password",
  "password": "Error pass"
}

###
DELETE http://localhost:3000/movies/6744a788ed0538a2e7e66688
Content-Type: application/json

