###
GET http://localhost:3000/

###
GET http://localhost:3000/movies

###
GET http://localhost:3000/movies?genre=Action

###
GET http://localhost:3000/movies/dcdd0fad-a94c-4810-8acc-5f108d3b18c3

###
GET http://localhost:3000/movies/idDoNotExist
